name: Run Web Scraper

on:
  schedule:
    - cron: '0 * * * *'  # Run every hour
  workflow_dispatch:  # Allows manual trigger

permissions:
  contents: write  # Explicitly set write permission to repository contents

jobs:
  run_scraper:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run Scraper
      run: python webscrapper_no_browserless.py

    - name: Commit and push generated JSON file
      run: |
        git config --global user.email "joaosfvieira@hotmail.com"
        git config --global user.name "GitHub Actions"
        git add jogadores.json
        git commit -m "Add scraped JSON data"
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/joaosfvieira/pdg-company.git
      env:
        # Use a GitHub token to authenticate
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
