name: Trigger Web Scraper

on:
  schedule:
    - cron: "0 * * * *"  # Executa a cada 1 hora

  workflow_dispatch:  # Permite execução manual pelo GitHub Actions

jobs:
  trigger-scraper:
    runs-on: ubuntu-latest
    steps:
      - name: Chamar a API do Flask para rodar o scraper
        run: |
          curl -X GET "https://pdg-company.vercel.app/run-scraper"
